---
sudo: false
language: python

python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'

env:
  PYTHONPATH: .:modules/mysql-connector-python:resources/lib:test
  PYTHONIOENCODING: utf-8

install:
- pip install -r requirements.txt

script:
- tox
- tox -e flake8
- pylint resources/lib/ test/
#- coverage run -m unittest discover
#- coverage run -a service.py
#- sleep 10
#- coverage run -a test/run.py /directory/root
#- coverage run -a test/run.py /directory/profiles
#- coverage run -a test/run.py /directory/home
#- coverage run -a test/run.py /directory/video_list_sorted/myList/queue
#- coverage run -a test/run.py /directory/video_list_sorted/newRelease/newRelease
#- coverage run -a test/run.py /directory/video_list/continueWatching/continueWatching
#- coverage run -a test/run.py /directory/video_list/chosenForYou/topTen
#- coverage run -a test/run.py /directory/video_list/recentlyAdded/1592210
#- coverage run -a test/run.py /directory/show/80057281/
#- pkill -f service.py

after_success:
- codecov
